/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Login.LOGIN;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import proyectprogra2.Conexion;

/**
 *
 * @author HP
 */
public class MENU extends javax.swing.JFrame {

    Conexion co = new Conexion();
    Connection con = co.conexiondb();
    String tipUser="";
    //recibe el dato del Login
    public static String usu;

    /**
     * Creates new form JF2
    */
    
    //Eliminar Forms
    /*
            JF7
            JF10
            JF13
            JF16
     */
    
    public MENU() {
        initComponents();
        datosGen();
        tipoUsuario();
    }

    public void datosGen() {
        String[] registros = new String[4];
        String docente = "";
        String sql = "CALL p_usuario('" + usu + "');";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("d.nombres");
                registros[1] = rs.getString("d.apellido_pat");
                registros[2] = rs.getString("d.apellido_mat");
                registros[3] = rs.getString("r.denominacion");
            }
            docente = registros[1] + " " + registros[2] + " " + registros[0];
            tipUser=registros[3];
            lblNom.setText(" " + docente.toUpperCase());
            lblTipUsu.setText(" " + registros[3]);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener datos" + e.getMessage(), "Mensaje", 0);
        }
    }

    public void tipoUsuario() {
        switch (tipUser) {
            case "DOCENTE":
                btnNewPub.setVisible(true);
                btnPub.setVisible(true);
                btnInfArt.setVisible(true);
                btnValTip.setVisible(false);
                btnValRat.setVisible(false);
                btnValDir.setVisible(false);
                btnValDec.setVisible(false);
                break;
            case "COMISION-TIPIFICACIÓN":
                btnNewPub.setVisible(false);
                btnPub.setVisible(false);
                btnInfArt.setVisible(false);
                //Activo
                btnValTip.setVisible(true);
                btnValRat.setVisible(false);
                btnValDir.setVisible(false);
                btnValDec.setVisible(false);
                break;
            case "COMISION-RATIFICACION":
                btnNewPub.setVisible(false);
                btnPub.setVisible(false);
                btnInfArt.setVisible(false);
                btnValTip.setVisible(false);
                //Activo
                btnValRat.setVisible(true);
                btnValDir.setVisible(false);
                btnValDec.setVisible(false);
                break;
            case "DIRECTOR DE DEPARTAMENTO":
                btnNewPub.setVisible(false);
                btnPub.setVisible(false);
                btnInfArt.setVisible(false);
                btnValTip.setVisible(false);
                btnValRat.setVisible(false);
                //Activo
                btnValDir.setVisible(true);
                btnValDec.setVisible(false);
                break;
            case "DECANO":
                btnNewPub.setVisible(false);
                btnPub.setVisible(false);
                btnInfArt.setVisible(false);
                btnValTip.setVisible(false);
                btnValRat.setVisible(false);
                btnValDir.setVisible(false);
                //Activo
                btnValDec.setVisible(true);
                break;
                
            default:
                JOptionPane.showMessageDialog(rootPane, "Error en tipo de usuario","Mensaje",0);
                this.setVisible(false);
                new LOGIN().setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblTipUsu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNewPub = new javax.swing.JButton();
        btnPub = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnInfArt = new javax.swing.JButton();
        btnPro = new javax.swing.JButton();
        btnValTip = new javax.swing.JButton();
        btnValRat = new javax.swing.JButton();
        btnValDir = new javax.swing.JButton();
        btnValDec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("TIPO DE USUARIO:");

        lblNom.setText("jLabel3");

        jLabel5.setText("DOCENTE");

        btnExit.setText("LOGOUT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblTipUsu.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(lblTipUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTipUsu)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewPub.setBackground(new java.awt.Color(255, 0, 0));
        btnNewPub.setText("Nueva Publicación");
        btnNewPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPubActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 140, 40));

        btnPub.setBackground(new java.awt.Color(0, 204, 0));
        btnPub.setText("Publicaciones");
        btnPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPubActionPerformed(evt);
            }
        });
        jPanel2.add(btnPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 130, 40));

        jLabel6.setText("INTERFAS DE MENU PRINCIPAL");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 12, -1, -1));

        btnInfArt.setBackground(new java.awt.Color(0, 0, 204));
        btnInfArt.setText("Inf. Artículos");
        btnInfArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfArtActionPerformed(evt);
            }
        });
        jPanel2.add(btnInfArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 140, 40));

        btnPro.setBackground(new java.awt.Color(255, 255, 0));
        btnPro.setText("Perfil");
        btnPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProActionPerformed(evt);
            }
        });
        jPanel2.add(btnPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 260, 160));

        btnValTip.setBackground(new java.awt.Color(153, 0, 153));
        btnValTip.setText("Validar");
        btnValTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValTipActionPerformed(evt);
            }
        });
        jPanel2.add(btnValTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, 40));

        btnValRat.setBackground(new java.awt.Color(204, 0, 0));
        btnValRat.setText("Validar");
        btnValRat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValRatActionPerformed(evt);
            }
        });
        jPanel2.add(btnValRat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, 40));

        btnValDir.setBackground(new java.awt.Color(0, 204, 255));
        btnValDir.setText("Validar");
        btnValDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValDirActionPerformed(evt);
            }
        });
        jPanel2.add(btnValDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 120, 40));

        btnValDec.setBackground(new java.awt.Color(153, 102, 0));
        btnValDec.setText("Validar");
        btnValDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValDecActionPerformed(evt);
            }
        });
        jPanel2.add(btnValDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 120, 40));

        jLabel3.setText("comTip");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("comRat");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel7.setText("Director");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel8.setText("Decano");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel9.setText("Docente");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        LOGIN lg = new LOGIN();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPubActionPerformed
        NUEVA_PUBLICACION.usu4 = usu;
        NUEVA_PUBLICACION jf4 = new NUEVA_PUBLICACION();
        jf4.setVisible(true);
    }//GEN-LAST:event_btnNewPubActionPerformed

    private void btnPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPubActionPerformed
        PUBLICACIONES_DOCENTE.usu5 = usu;
        PUBLICACIONES_DOCENTE jf5 = new PUBLICACIONES_DOCENTE();
        jf5.setVisible(true);
    }//GEN-LAST:event_btnPubActionPerformed

    private void btnInfArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfArtActionPerformed
        ARTICULOS.usu6 = usu;
        ARTICULOS jf6 = new ARTICULOS();
        jf6.setVisible(true);
    }//GEN-LAST:event_btnInfArtActionPerformed

    private void btnProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProActionPerformed
        EDITAR_PERFIL.usu3 = usu;
        EDITAR_PERFIL jf3 = new EDITAR_PERFIL();
        jf3.setVisible(true);

    }//GEN-LAST:event_btnProActionPerformed

    private void btnValTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValTipActionPerformed
        new LISTA_TIPIFICACION().setVisible(true);
    }//GEN-LAST:event_btnValTipActionPerformed

    private void btnValRatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValRatActionPerformed
        new LISTA_RATIFICACION().setVisible(true);
    }//GEN-LAST:event_btnValRatActionPerformed

    private void btnValDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValDirActionPerformed
        new LISTA_DIRECTOR().setVisible(true);
    }//GEN-LAST:event_btnValDirActionPerformed

    private void btnValDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValDecActionPerformed
        new LISTA_DECANO().setVisible(true);
    }//GEN-LAST:event_btnValDecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInfArt;
    private javax.swing.JButton btnNewPub;
    private javax.swing.JButton btnPro;
    private javax.swing.JButton btnPub;
    private javax.swing.JButton btnValDec;
    private javax.swing.JButton btnValDir;
    private javax.swing.JButton btnValRat;
    private javax.swing.JButton btnValTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblTipUsu;
    // End of variables declaration//GEN-END:variables
}
